import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "../globals.css";

import MenuMobile from "@/components/MenuMobile";
import MobileBar from "@/components/MobileBar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <body className={outfit.className}>
        <MobileBar>
          <MenuMobile />
        </MobileBar>
        <Sidebar />
        <main className="px-4 pt-24 sm:px-12 lg:p-12 lg:pl-[calc(250px+50px)] lg:pr-[50px]">
          {children}
        </main>
      </body>
    </html>
  );
}
